### ISSUE TITLE
Caption under molecule!

### ISSUE THREAD

**Issue by Martin-2025s** [aminophen/chemobabel#5]
Dear Maintainer!

I would kindly ask You to consider the possibility of adding a caption to the structure of the molecule - generated by Your LaTeX package; with options such as font size and colour.

This would be extremely helpful :-)

Martin

**Comment by aminophen** [comment]
Thanks for your comment.

\chemobabel is merely a wrapper for \includegraphics, so you can simply use \caption inside \begin{figure} ... \end{figure}. Isn't it enough? Or, do you mean something else?

**Comment by Martin-2025s** [comment]
Dear Creator!

Indeed, the simplest solutions are the most effective. Nevertheless, the possibility of signing molecules and creating a grid (matrix), e.g. 4 molecules by 4 molecules, is on my mind, and only this as a so-called "Drawing Inset" into LaTeX figure.


Thank you for your quick reply and congratulations on a very good package!

Martin
