### ISSUE TITLE
Eliminate error from mkdir when directory already exists

### ISSUE THREAD

**Issue by daniel-anavaino** [aminophen/chemobabel#6]
Adding the '-p' option to mkdir in [chemobabel.sty](https://github.com/aminophen/chemobabel/blob/master/chemobabel.sty) will eliminate the reported error when the directory already exists.

**Comment by aminophen** [comment]
Thanks for the suggestion but I have to keep the package working on windows; 'mkdir' of windows (command prompt) does not accept -p option.
