### ISSUE TITLE
Strict size definitions of bonds and atom(s) sizes

### ISSUE THREAD

**Issue by Martin-2025s** [aminophen/chemobabel#7]
Dear Author!

I would like to kindly ask you to consider the question, the following adaptation of the package, in which the length of the bonds and the size of the atoms can be strictly defined;
this would give the possibility of a reproducible and graphically consistent depiction of molecules in a single document.
Currently, I cannot achieve this...

Thank you in advance for Your such a great work!

M

**Comment by aminophen** [comment]
Sorry, but it depends on whether the obabel program itself supports it. The only thing the "chemobabel" package can do is to include the result of an obabel 2D depiction (SVG). First, ask the [Open Babel folks](http://openbabel.org/index.html) if their 2D depiction supports fixing all bond lengths and text sizes.

**Comment by Martin-2025s** [comment]
Thank You for your answer.
